all:
	$(MAKE) -C core/src/cpp -f Makefile all
	$(MAKE) -C audio/src/cpp -f Makefile all

clean:
	$(MAKE) -C core/src/cpp -f Makefile clean
	$(MAKE) -C audio/src/cpp -f Makefile clean

.PHONY: all clean